project:
  type: book
  output-dir: docs

book:
  title: "Econometría con R"
  author: "Pau Orive Vidal"
  date: today
  description: "Libro online para aprender a manipular y analizar datos mediante técnicas econométricas y de ciencia de datos con R"
  repo-url: https://github.com/PauOrive/econometria_con_r
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - 01_intro_al_libro.qmd
    - part: "Importar, manipular y visualizar datos"
      chapters:
        - 10_intro_a_r.qmd
        - 11_importar_datos.qmd
        - 12_exploracion_inicial.qmd
        - 13_manipulacion_datasets.qmd
        - 14_visualizacion_estatica.qmd
        - 15_visualizacion_interactiva.qmd
        - 16_datos_geoespaciales.qmd
    - part: "Fundamentos de econometría"
      chapters:
        - 20_proceso_econometrico.qmd
        - 21_fundamentos_matematicos.qmd
        - 22_poblacion_muestra.qmd
        - 23_especificar_modelo.qmd
        - 24_modelo_regresion.qmd
        - 25_tecnica_estimacion.qmd
        - 26_inferencia.qmd
        - 27_variable_dependiente_limitada.qmd
        - 28_datos_de_panel.qmd
        - 29_series_temporales.qmd
    - part: "Inferencia causal"
      chapters:
      # reordenar
        - 30_marco_conceptual.qmd
        - 31_variables_instrumentales.qmd 
        - 32_rct.qmd
        - 33_matching.qmd
        - 34_diff_in_diff.qmd
        - 35_control_sintetico.qmd
        - 36_regresion_discontinuidad.qmd       
    #- part: "Data Science"
     # chapters:
      # aún por definir
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true
    number-sections: true

editor: visual

